FROM alpine:3.21.3

WORKDIR /app
COPY . .
RUN apk add --no-cache python3 py3-pip tzdata
RUN export PIP_BREAK_SYSTEM_PACKAGES=1; pip3 install --no-cache-dir -Ur /app/requirements.txt

VOLUME /downloads

ENTRYPOINT ["python3", "dropbot.py"]